### ISSUE TITLE
Can´t connect to a Teamspeak Server

### ISSUE THREAD

**Issue by CodeStrings** [Manevolent/ts3j#1]
I first tried with the test example in ServerConnectionTest, that worked great for me with the example Teamspeak Server, as soon as I try any other TeamSpeak I can´t connect and get a timeout, while waiting for  the CONNECTED state

**Comment by Manevolent** [comment]
You may want to set Ts3Debugging stuff to on, project is kindof funny with how that's all set up but it may give you some insight as to why that is happening in the form of a stack trace.  Sounds like an INIT packet is failing and going unanswered somewhere.

**Comment by CodeStrings** [comment]
Thanks for the answer, After selecting the direct API it worked ;) But another Bug that I found is that you cant view the Information about the Client the Debug shows no Packet is defined for that and also the Windows Version is not shown correctly ;( And is it also possible to make a Voice Packet with a size over 500?

**Comment by Manevolent** [comment]
OK so that sounds like TSDNS?  I haven't done that part yet so that would explain it.

Oh and, right now I haven't implemented the client info... it'll just show retrieving right now but it's doing no harm stability wise, just a tad weird.

You can't send a voice packet over 500 bytes, well technically you could if you would compress it first, but ideally you want to segment your voice data into, well, packets.  What I'm doing is I'm using an Opus wrapper for Java, and encoding 20ms at a time.  Then, I implement the interface and report OPUS_MUSIC as the type, and when provide() is called I simply offer up an encoding of the 20ms of audio, which for Opus munis stereo is 960 samples/shorts/floats or something like that.  If you want the code I can probably push up a test for that too.

**Comment by CodeStrings** [comment]
Would Be nice of I could the Code ;) My Problem is that I would like to directly Stream the Music from YouTube, because I want to achieve a minimal load. But when I try that the Packets are like 300-700 big. Maybe we can Write in Discord: Yonathan#5560

**Comment by Manevolent** [comment]
Well unless it's a code change in ts3j I think you will run into trouble, I don't think you willt be able to see the notification command/event pop by since I sort of filter those out from the command handler part of the code.  What I need to do is gander through Splamy's (gold standard for TS3 client) code and see how they did it.
