### ISSUE TITLE
Change volume/gain filter 

### ISSUE THREAD

**Issue by Pieprzyk** [Manevolent/ts3j#10]
Changing Q parametter from 20.0 to 0.0 change only audio output I mean while it's closer to 0 muisc is louder in left speaker and while it's closer to 20.0 music bass i boosted and it sound like distortion of sound

/**
 * Compresses an audio signal (analog).
 *
 * When Q is closer to 0, the signal volume is increased.
 * When Q is 1, the signal volume is not modified.
 * When Q is closer to infinity, the signal volume is reduced.
 */
public class FilterGain implements MixerFilter {
    private float q;

    public FilterGain(float q) {
        this.q = q;
    }

    public void setQ(float q) {
        this.q = q;
    }

    public float getQ() {
        return q;
    }

    @Override
    public int process(float[] samples, int offs, int len) {
        for (int i = 0; i < len; i ++) {
            samples[i] = samples[i] * q;
        }

        return len - offs;
    }
}

Maven dependencies

<dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.8.1</version>
        </dependency>

        <dependency>
            <groupId>net.tomp2p</groupId>
            <artifactId>opus-wrapper</artifactId>
            <version>1.4</version>
        </dependency>

        
        <dependency>
            <groupId>com.sun.jna</groupId>
            <artifactId>jna</artifactId>
            <version>3.0.9</version>
        </dependency>

        
        <dependency>
            <groupId>com.github.manevolent</groupId>
            <artifactId>ts3j</artifactId>
            <version>-SNAPSHOT</version>
        </dependency>

        
        <dependency>
            <groupId>com.github.manevolent</groupId>
            <artifactId>ffmpeg4j</artifactId>
            <version>4ce451b</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.5</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>
    </dependencies>

**Comment by Manevolent** [comment]
Couple things:

1. I think you meant to put this issue on the project: https://github.com/manevolent/ts3j-musicbot.  But, I might be wrong here.  I don't think ts3j itself has audio filters, like FilterGain.
2. When you set Q to 20.0, the audio is **20 times louder**!  So, an audio sample value of 0.1 would become 2.0, which is way too loud to encode reliably -- it'll be "clipped", and set to 1.0.  This is where your bass distortion is coming from.  When it's set to 0, it's louder on the left because the right channel is zero'd -- a sample of 0.1 * 0.0 == 0.0, so it's effectively muted.
3.  Sounds like the filters are not _stereo_, which is a problem I can address.  Can you put this issue on the project you're using, which I assume is ts3j-musicbot?
