### ISSUE TITLE
Repository error

### ISSUE THREAD

**Issue by dshimen** [Manevolent/ts3j#43]
https://repo.manebot.io/repository/public

That repository has 503 error which blocks maven from downloading libs.

**Comment by Manevolent** [comment]
Did you mean to open this issue on a Manebot repository?  I looked through dependencies on ts3j and didn't see one that would live in that repository.  Also, ts3j shouldn't need that repo regardless.  Can you close the issue here and open it on the Manebot repository that you need help with specifically?

More specific to the problem itself, I do host that and I am thinking a regular patch cycle I have on server maintenance failed.  It's a load balanced reverse proxy and I'm guessing the origin containers are all unavailable due to some sort of update-related error.

**Comment by dshimen** [comment]
Problem was solved by downloading from github all: media/audio/plugin libs and installing them with maven.
